name: daison
version: 0.1.0.0

dependencies:
  - base

library:
  source-dirs: src
  c-sources: 
    - src/c/sqlite3Btree.c
  dependencies:
    - base
    - text
    - binary
    - syb
    - bytestring
    - containers
    - random
    - criterion
  include-dirs: src/c

    
  ghc-options:
    - -Wall
    # TODO: FIX THESE!
    - -Wno-orphans
    - -Wno-missing-methods
    - -Wno-incomplete-patterns
  build-tools: hsc2hs

executables:
  main-exe:
    main: MainProject.hs
    other-modules:
      AILabel
      DAILabel
      DAILabelModified
      Paths_daison

    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - daison
      - containers
      - ghc-prim
      - QuickCheck
      - process
      - random
      - criterion
      - directory
      - time