name: daison
version: 0.1.0.0

dependencies:
  - base

library:
  source-dirs: src
  c-sources: 
    - src/c/sqlite3Btree.c
  dependencies:
    - base
    - text
    - binary
    - syb
    - bytestring
    - containers
    - random
  include-dirs: src/c

    
  ghc-options:
    - -Wall
    # TODO: FIX THESE!
    - -Wno-orphans
    - -Wno-missing-methods
    - -Wno-incomplete-patterns
  build-tools: hsc2hs

executables:
  daison-exe:
    main: DAILabel.hs
    other-modules:
#      AILabelToDynamic
#      DAILabel
      Paths_daison

    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - daison
      - containers
      - ghc-prim
      - QuickCheck
      - process
      - random
  ailabel-exe:
    main: AILabel.hs
    other-modules:
#      AILabelToDynamic
#      DAILabel
      Paths_daison

    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - daison
      - containers
      - ghc-prim
      - QuickCheck
      - process
      - random
  mdailabel-exe:
    main: DAILabelModified.hs
    other-modules:
#      AILabelToDynamic
#      DAILabel
      Paths_daison

    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - daison
      - containers
      - ghc-prim
      - QuickCheck
      - process
      - random